# JerryScript 
COMPONENT_SUBMODULES := jerryscript

JERRYSCRIPT_CORE := $(COMPONENT_PATH)/jerryscript/jerry-core
COMPONENT_SRCDIRS := $(call ListAllSubDirs,$(JERRYSCRIPT_CORE))
COMPONENT_INCDIRS := jerryscript $(JERRYSCRIPT_CORE) $(COMPONENT_SRCDIRS)

# The size of the JerryScript engine heap. The size in kilobytes is allocated once and defined at compile time.
COMPONENT_VARS := JERRY_GLOBAL_HEAP_SIZE
JERRY_GLOBAL_HEAP_SIZE ?= 1

# Compact compilation profile makes the JerryScript library smaller
COMPONENT_VARS += JERRY_COMPACT_PROFILE  
JERRY_COMPACT_PROFILE ?= 1

ifeq ($(JERRY_COMPACT_PROFILE),1)
	COMPONENT_CFLAGS += \
		-DJERRY_BUILTINS=0 \
		-DJERRY_ES2015=0 \
		-DJERRY_UNICODE_CASE_CONVERSION=0
endif

COMPONENT_CFLAGS += \
	-DJERRY_NUMBER_TYPE_FLOAT64=0 \
	-DJERRY_GLOBAL_HEAP_SIZE=$(JERRY_GLOBAL_HEAP_SIZE) \
	-DJERRY_LCACHE=0  \
	-DJERRY_PARSER=0 \
	-DJERRY_SNAPSHOT_EXEC=1 \
	-DJERRY_NDEBUG
